extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/core/*.bril'
timeout = 100

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.lvn]
pipeline = [
    "bril2json",
    "./lvn",
    "../tdce/tdce",
    "brili -p {args}"
]
