extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/core/*.bril'
timeout = 100

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.tdce]
pipeline = [
    "bril2json",
    "./tdce",
    "brili -p {args}"
]
